### ISSUE TITLE
Ignorar .instagram-media

### ISSUE THREAD

**Issue by vcano5** [PhantomInsights/summarizer#1]
En [este enlace](https://www.reddit.com/r/mexico/comments/hcr7m0/destapan_red_de_tr%C3%A1fico_de_ni%C3%B1os_mayas_en_yucat%C3%A1n/fvgnze0/) el bot incluyo en el resumen una noticia que esta en el instagram de la pagina

**Comment by vcano5** [comment]
#2

**Comment by agentphantom** [comment]
Muchas gracias, ya incorpore el PR.
